# Nama Alur Kerja (Workflow)
name: Deploy Firebase Cloud Functions

# Trigger: Kapan alur kerja ini berjalan
on:
  push:
    branches:
      - main  
    paths:
      - '.github/**'
      - 'functions/**' # Hanya deploy jika ada perubahan di folder 'functions'

jobs:
  deploy:
    name: Deploy Functions
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout kode dari repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup Node.js 18
      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Instal Firebase CLI (Secara Global)
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 4. Instal Dependensi Cloud Functions (Dijalankan di dalam folder 'functions')
      - name: Install Function Dependencies
        run: npm install
        working-directory: functions # <-- Ini memastikan npm install berjalan di folder yang benar

      # 5. Deploy ke Firebase (Dari Root, tapi menargetkan folder 'functions')
      - name: Deploy Functions
        run: firebase deploy --only functions --token "${{ secrets.FIREBASE_DEPLOY_TOKEN }}" --project ${{ env.FIREBASE_PROJECT }}
        env:
          # Variabel lingkungan untuk Project ID (disimpan juga sebagai env var)
          FIREBASE_PROJECT: androlin-4028a # <-- PASTIKAN INI ADALAH PROJECT ID ANDA
          
          # Variabel rahasia untuk Cloud Functions
          MIDTRANS_SECRET_KEY: ${{ secrets.MIDTRANS_SECRET_KEY }} 
          NODE_ENV: "development"
          
